#!/usr/bin/env python
# Emacs, this is -*-Python-*-
"""
Generate a DOT (in Graphviz) file from tulipcon XML file.

Note this is basically a wrapper to ease use of the Automaton class
and its writeDotFile method from the command-line. Accepts a *.xml
filename and, optionally, a destination filename. If no destination is
given, default is to use input filename with new ending ".dot"

By default in each state node, variables taking the value zero are not
listed.  To disable this (i.e., do not hide any valuations), use the
flag "-z".

Also note that command-line arguments are handled manually, since they
are so simple...

Example: suppose you have robotctrl.xml from a TuLiP session. Then to
generate a corresponding DOT file and create a PNG image, try

$ xml2dot robotctrl.xml
$ dot -Tpng -O robotctrl.dot

Depending on your graphviz installation, the resulting image file may
be called robotctrl.dot.png
"""

import sys
from tulip.automaton import Automaton
from tulip.conxml import loadXML

if __name__ == "__main__":
    if "-h" in sys.argv or len(sys.argv) < 2 or len(sys.argv) > 5:
        print "Usage: xml2dot [-zh] INPUT [OUTPUT]\n"
        print "  -h        this help message."
        print "  -z        do not hide names of variables that are false at a node."
        print "  -c        color nodes according to goal mode."
        print "  -a        label nodes with attributes (requires -c flag)."
        print "  INPUT     name of file to read from; if \"-\", then read from stdin."
        print "  OUTPUT    name of file to write to;"
        print "            if \"-\" (default if INPUT is -), then write to stdout."
        exit(1)

    # Detect and strip flags
    if "-z" in sys.argv:
        hidez_flag = False
        sys.argv.remove("-z")
    else:
        hidez_flag = True
    if "-c" in sys.argv:
        colormodes_flag = True
        sys.argv.remove("-c")
    else:
        colormodes_flag = False
    if "-a" in sys.argv:
        nodeattrib_flag = colormodes_flag
        sys.argv.remove("-a")
    else:
        nodeattrib_flag = False

    if len(sys.argv) == 2 and sys.argv[1] == "-":
        destfile = "-"
    else:
        if len(sys.argv) == 3:
            destfile = sys.argv[2]
        else:
            if len(sys.argv[1]) < 4:  # Handle weirdly short names
                destfile = sys.argv[1] + ".dot"
            else:
                destfile = sys.argv[1][:-4] + ".dot"
    
    if sys.argv[1] == "-":
        (prob, sys_dyn, aut) = loadXML(sys.stdin.read())
    else:
        with open(sys.argv[1], "r") as f:
            (prob, sys_dyn, aut) = loadXML(f.read())
    if colormodes_flag:
        dump_method = aut.dumpDOTcolor
    else:
        dump_method = aut.dumpDOT
    if destfile == "-":
        if nodeattrib_flag:
            print dump_method(hideZeros=hidez_flag, node_attrib=True)
        else:
            print dump_method(hideZeros=hidez_flag)
    else:
        with open(destfile, "w") as f:
            if nodeattrib_flag:
                f.write(dump_method(hideZeros=hidez_flag, node_attrib=True))
            else:
                f.write(dump_method(hideZeros=hidez_flag))
